/**
 * Copy for `/admin/*` (JWT + server-side GraphQL). Split from `i18n.ts` so route modules
 * never hit partial `i18n` evaluation during circular loads.
 */

import { DEFAULT_LOCALE, type Locale } from './i18n.ts';

export function adminCopy(locale: Locale) {
  const t = {
    en: {
      shellTitle: 'Admin',
      shellAsideAria: 'Admin navigation',
      navDashboard: 'Dashboard',
      navArticles: 'News',
      navFlashes: 'Wire',
      navHeroes: 'Hero',
      navAnalytics: 'Live traffic',
      backSite: '← Site',
      dashTitle: 'Dashboard',
      /** Shown under the title when CMS stats load successfully. */
      dashLeadOk: 'Published content and CMS metrics at a glance.',
      /** Single message when stats could not be loaded (warn box only — no duplicate subtitle). */
      dashUnavailable:
        'Could not load CMS stats. Fix the connection below (same secrets as mongo/backend, API running, correct URL).',
      dashUnavailableErrorLabel: 'Last error',
      dashUnavailableStepsTitle: 'Checklist',
      dashStepSecret:
        'In news/.env, NEXUS_ADMIN_SECRET must match ADMIN_SECRET in mongo/backend/.env exactly (character for character, no extra spaces).',
      dashStepBackend: 'Start the API: cd mongo/backend && npm run dev (listen on port 4000 by default).',
      dashStepUrl:
        'In news/.env, NEXUS_GRAPHQL_URL must point at the GraphQL endpoint (default http://127.0.0.1:4000/graphql).',
      dashInventoryIntro:
        'All CMS records below: articles, wire, hero banners, plus tags and authors. Edit or delete where actions are available.',
      dashSectionNews: 'News',
      dashSectionFlash: 'Wire flashes',
      dashSectionHero: 'Hero banners',
      dashSectionMeta: 'Tags and authors',
      dashListLoadFailed:
        'Could not load this list. Check connection, NEXUS_GRAPHQL_URL, and that NEXUS_ADMIN_SECRET matches ADMIN_SECRET.',
      dashMetaReadOnly:
        'Tags and authors are read-only here. Assign them when editing articles; author bios live in CMS data.',
      tagColName: 'Name',
      tagColSlug: 'Slug',
      tagEmpty: 'No tags in the database yet.',
      authorColName: 'Name',
      authorColId: 'ID',
      authorEmpty: 'No authors in the database yet.',
      dashViewAll: 'View all',
      dashColActions: 'Actions',
      dashEdit: 'Edit',
      dashDelete: 'Delete',
      dashDeleteFail: 'Could not delete.',
      kpiArticlesPub: 'Articles published',
      kpiFlashPub: 'Wire items published',
      kpiTotal: 'total',
      kpiWireShown: 'in sample (max 24)',
      kpiHeroes: 'Hero rows',
      kpiTags: 'Tags',
      kpiAuthors: 'Authors',
      analyticsTitle: 'Live traffic',
      analyticsLead:
        'Recent page views on this Nexus process. IP is kept server-side only; live SSE rows omit IP.',
      colTime: 'Time',
      colPath: 'Path',
      colHost: 'Host',
      colRef: 'Referrer',
      colUa: 'User agent',
      colIp: 'IP',
      liveBadge: 'Live',
      emptyVisits: 'No visits yet — open the public site in another tab.',
      articleListTitle: 'Articles',
      articleBackList: '← Articles',
      articleNew: 'New article',
      articleEdit: 'Edit article',
      articleColTitle: 'Title',
      articleColSlug: 'Slug',
      articleColStatus: 'Status',
      articleColUpdated: 'Updated',
      articleStatusPub: 'Published',
      articleStatusDraft: 'Draft',
      articleEmpty: 'No articles yet. Create one to get started.',
      articleFormTitleLabel: 'Title',
      articleFormSlugLabel: 'URL slug',
      articleFormExcerptLabel: 'Excerpt',
      articleFormContentLabel: 'Body (HTML or plain text)',
      articleFormCoverLabel: 'Cover image URL',
      articleFormCoverAltLabel: 'Cover alt text',
      articleFormReadTimeLabel: 'Read time (minutes)',
      articleFormAuthorLabel: 'Author',
      articleFormAuthorNone: '— None —',
      articleFormTagsLabel: 'Tags',
      articleFormPublishedLabel: 'Published',
      articleFormSave: 'Save',
      articleFormDelete: 'Delete article',
      articleFormDeleteConfirm: 'Delete this article permanently?',
      articleErrSave: 'Could not save. Check fields and CMS connection.',
      adminMediaUploadLabel: 'Image file (Cloudinary)',
      adminMediaUploadHint:
        'Upload sends the file to the API; the cover URL field is filled automatically. You can still paste a URL by hand.',
      adminMediaUploadErr: 'Image upload failed. Check admin session and API (CORS / same origin).',
      flashListTitle: 'Wire flashes',
      flashBackList: '← Wire',
      flashNew: 'New flash',
      flashEdit: 'Edit flash',
      flashColTitle: 'Title',
      flashColSlug: 'Slug',
      flashColStatus: 'Status',
      flashColUpdated: 'Updated',
      flashEmpty: 'No wire items yet.',
      flashStatusPub: 'Published',
      flashStatusDraft: 'Draft',
      flashFormTitleLabel: 'Title',
      flashFormSlugLabel: 'Slug (optional; generated from title if empty)',
      flashFormSummaryLabel: 'Summary',
      flashFormSourceLabel: 'Source label',
      flashFormSourceUrlLabel: 'Source URL',
      flashFormHackLabel: 'Note',
      flashFormPublishedLabel: 'Published',
      flashFormSave: 'Save',
      flashFormDelete: 'Delete',
      flashFormDeleteConfirm: 'Delete this wire item permanently?',
      flashErrSave: 'Could not save. Check fields and CMS connection.',
      heroListTitle: 'Hero banners',
      heroBackList: '← Hero',
      heroNew: 'New hero block',
      heroEdit: 'Edit hero',
      heroColSlug: 'Slug',
      heroColHeadline: 'Headline',
      heroColStatus: 'Status',
      heroColUpdated: 'Updated',
      heroEmpty: 'No hero blocks yet.',
      heroStatusPub: 'Published',
      heroStatusDraft: 'Draft',
      heroFormSlugLabel: 'Slug',
      heroFormSlugHint: 'Stable key (e.g. home). Cannot be changed after save.',
      heroFormKickerLabel: 'Kicker',
      heroFormHeadlineLabel: 'Headline',
      heroFormSubheadlineLabel: 'Subheadline',
      heroFormBodyLabel: 'Body',
      heroFormBodySecondaryLabel: 'Secondary body',
      heroFormImageUrlLabel: 'Image URL',
      heroFormFooterCtaLabel: 'Footer CTA label',
      heroFormFooterCtaHrefLabel: 'Footer CTA URL',
      heroFormPublishedLabel: 'Published',
      heroFormSave: 'Save',
      heroFormDelete: 'Delete hero',
      heroFormDeleteConfirm: 'Delete this hero block permanently?',
      heroErrSave: 'Could not save. Check fields and CMS connection.',
    },
    es: {
      shellTitle: 'Admin',
      shellAsideAria: 'Navegación de administración',
      navDashboard: 'Panel',
      navArticles: 'Noticias',
      navFlashes: 'Cable',
      navHeroes: 'Hero',
      navAnalytics: 'Tráfico en vivo',
      backSite: '← Sitio',
      dashTitle: 'Panel',
      dashLeadOk: 'Resumen de contenido publicado y métricas del CMS.',
      dashUnavailable:
        'No se pudieron cargar las estadísticas del CMS. Revisa la conexión (mismos secretos que mongo/backend, API en marcha, URL correcta).',
      dashUnavailableErrorLabel: 'Último error',
      dashUnavailableStepsTitle: 'Lista de comprobación',
      dashStepSecret:
        'En news/.env, NEXUS_ADMIN_SECRET debe coincidir exactamente con ADMIN_SECRET en mongo/backend/.env (carácter a carácter, sin espacios de más).',
      dashStepBackend: 'Arranca el API: cd mongo/backend && npm run dev (puerto 4000 por defecto).',
      dashStepUrl:
        'En news/.env, NEXUS_GRAPHQL_URL debe apuntar al endpoint GraphQL (por defecto http://127.0.0.1:4000/graphql).',
      dashInventoryIntro:
        'Todos los registros del CMS: noticias, cable, banners hero, más etiquetas y autores. Edita o elimina donde haya acciones.',
      dashSectionNews: 'Noticias',
      dashSectionFlash: 'Cable / flashes',
      dashSectionHero: 'Banners hero',
      dashSectionMeta: 'Etiquetas y autores',
      dashListLoadFailed:
        'No se pudo cargar esta lista. Revisa la conexión, NEXUS_GRAPHQL_URL y que NEXUS_ADMIN_SECRET coincida con ADMIN_SECRET.',
      dashMetaReadOnly:
        'Etiquetas y autores son solo lectura aquí. Asígnalos al editar artículos; las biografías están en los datos del CMS.',
      tagColName: 'Nombre',
      tagColSlug: 'Slug',
      tagEmpty: 'Aún no hay etiquetas en la base de datos.',
      authorColName: 'Nombre',
      authorColId: 'ID',
      authorEmpty: 'Aún no hay autores en la base de datos.',
      dashViewAll: 'Ver todo',
      dashColActions: 'Acciones',
      dashEdit: 'Editar',
      dashDelete: 'Eliminar',
      dashDeleteFail: 'No se pudo eliminar.',
      kpiArticlesPub: 'Artículos publicados',
      kpiFlashPub: 'Cable publicado',
      kpiTotal: 'total',
      kpiWireShown: 'en muestra (máx. 24)',
      kpiHeroes: 'Filas hero',
      kpiTags: 'Etiquetas',
      kpiAuthors: 'Autores',
      analyticsTitle: 'Tráfico en vivo',
      analyticsLead:
        'Vistas recientes en este proceso de Nexus. La IP solo se guarda en el servidor; el SSE en vivo no la envía.',
      colTime: 'Hora',
      colPath: 'Ruta',
      colHost: 'Host',
      colRef: 'Referrer',
      colUa: 'User agent',
      colIp: 'IP',
      liveBadge: 'En vivo',
      emptyVisits: 'Aún no hay visitas — abre el sitio público en otra pestaña.',
      articleListTitle: 'Artículos',
      articleBackList: '← Artículos',
      articleNew: 'Nuevo artículo',
      articleEdit: 'Editar artículo',
      articleColTitle: 'Título',
      articleColSlug: 'Slug',
      articleColStatus: 'Estado',
      articleColUpdated: 'Actualizado',
      articleStatusPub: 'Publicado',
      articleStatusDraft: 'Borrador',
      articleEmpty: 'Aún no hay artículos. Crea uno para empezar.',
      articleFormTitleLabel: 'Título',
      articleFormSlugLabel: 'Slug URL',
      articleFormExcerptLabel: 'Resumen',
      articleFormContentLabel: 'Cuerpo (HTML o texto)',
      articleFormCoverLabel: 'URL imagen de portada',
      articleFormCoverAltLabel: 'Texto alternativo',
      articleFormReadTimeLabel: 'Tiempo de lectura (min)',
      articleFormAuthorLabel: 'Autor',
      articleFormAuthorNone: '— Ninguno —',
      articleFormTagsLabel: 'Etiquetas',
      articleFormPublishedLabel: 'Publicado',
      articleFormSave: 'Guardar',
      articleFormDelete: 'Eliminar artículo',
      articleFormDeleteConfirm: '¿Eliminar este artículo para siempre?',
      articleErrSave: 'No se pudo guardar. Revisa los campos y la conexión al CMS.',
      adminMediaUploadLabel: 'Archivo de imagen (Cloudinary)',
      adminMediaUploadHint:
        'La subida va al API y rellena solo el campo de URL de portada. También puedes pegar una URL manualmente.',
      adminMediaUploadErr: 'Error al subir la imagen. Revisa sesión de admin y API (CORS).',
      flashListTitle: 'Cable / flashes',
      flashBackList: '← Cable',
      flashNew: 'Nuevo flash',
      flashEdit: 'Editar flash',
      flashColTitle: 'Título',
      flashColSlug: 'Slug',
      flashColStatus: 'Estado',
      flashColUpdated: 'Actualizado',
      flashEmpty: 'Aún no hay ítems de cable.',
      flashStatusPub: 'Publicado',
      flashStatusDraft: 'Borrador',
      flashFormTitleLabel: 'Título',
      flashFormSlugLabel: 'Slug (opcional; se genera del título si va vacío)',
      flashFormSummaryLabel: 'Resumen',
      flashFormSourceLabel: 'Etiqueta de fuente',
      flashFormSourceUrlLabel: 'URL de fuente',
      flashFormHackLabel: 'Nota',
      flashFormPublishedLabel: 'Publicado',
      flashFormSave: 'Guardar',
      flashFormDelete: 'Eliminar',
      flashFormDeleteConfirm: '¿Eliminar este flash para siempre?',
      flashErrSave: 'No se pudo guardar. Revisa los campos y la conexión al CMS.',
      heroListTitle: 'Banners hero',
      heroBackList: '← Hero',
      heroNew: 'Nuevo bloque hero',
      heroEdit: 'Editar hero',
      heroColSlug: 'Slug',
      heroColHeadline: 'Titular',
      heroColStatus: 'Estado',
      heroColUpdated: 'Actualizado',
      heroEmpty: 'Aún no hay bloques hero.',
      heroStatusPub: 'Publicado',
      heroStatusDraft: 'Borrador',
      heroFormSlugLabel: 'Slug',
      heroFormSlugHint: 'Clave estable (p. ej. home). No se puede cambiar tras guardar.',
      heroFormKickerLabel: 'Antetítulo',
      heroFormHeadlineLabel: 'Titular',
      heroFormSubheadlineLabel: 'Subtítulo',
      heroFormBodyLabel: 'Cuerpo',
      heroFormBodySecondaryLabel: 'Cuerpo secundario',
      heroFormImageUrlLabel: 'URL de imagen',
      heroFormFooterCtaLabel: 'CTA pie (texto)',
      heroFormFooterCtaHrefLabel: 'CTA pie (URL)',
      heroFormPublishedLabel: 'Publicado',
      heroFormSave: 'Guardar',
      heroFormDelete: 'Eliminar hero',
      heroFormDeleteConfirm: '¿Eliminar este bloque hero para siempre?',
      heroErrSave: 'No se pudo guardar. Revisa los campos y la conexión al CMS.',
    },
    pt: {
      shellTitle: 'Admin',
      shellAsideAria: 'Navegação de administração',
      navDashboard: 'Painel',
      navArticles: 'Notícias',
      navFlashes: 'Fio',
      navHeroes: 'Hero',
      navAnalytics: 'Tráfego ao vivo',
      backSite: '← Site',
      dashTitle: 'Painel',
      dashLeadOk: 'Visão geral do conteúdo publicado e métricas do CMS.',
      dashUnavailable:
        'Não foi possível carregar as estatísticas do CMS. Verifique a ligação (mesmos segredos que mongo/backend, API a correr, URL correta).',
      dashUnavailableErrorLabel: 'Último erro',
      dashUnavailableStepsTitle: 'Lista de verificação',
      dashStepSecret:
        'Em news/.env, NEXUS_ADMIN_SECRET deve coincidir exatamente com ADMIN_SECRET em mongo/backend/.env (carácter a carácter, sem espaços a mais).',
      dashStepBackend: 'Inicie o API: cd mongo/backend && npm run dev (porta 4000 por omissão).',
      dashStepUrl:
        'Em news/.env, NEXUS_GRAPHQL_URL deve apontar para o endpoint GraphQL (predefinição http://127.0.0.1:4000/graphql).',
      dashInventoryIntro:
        'Todos os registos no CMS: notícias, fio, banners hero, mais etiquetas e autores. Edite ou elimine onde houver ações.',
      dashSectionNews: 'Notícias',
      dashSectionFlash: 'Fio / flashes',
      dashSectionHero: 'Banners hero',
      dashSectionMeta: 'Etiquetas e autores',
      dashListLoadFailed:
        'Não foi possível carregar esta lista. Verifique a ligação, NEXUS_GRAPHQL_URL e se NEXUS_ADMIN_SECRET coincide com ADMIN_SECRET.',
      dashMetaReadOnly:
        'Etiquetas e autores são só leitura aqui. Atribua-os ao editar artigos; biografias ficam nos dados do CMS.',
      tagColName: 'Nome',
      tagColSlug: 'Slug',
      tagEmpty: 'Ainda não há etiquetas na base de dados.',
      authorColName: 'Nome',
      authorColId: 'ID',
      authorEmpty: 'Ainda não há autores na base de dados.',
      dashViewAll: 'Ver tudo',
      dashColActions: 'Ações',
      dashEdit: 'Editar',
      dashDelete: 'Eliminar',
      dashDeleteFail: 'Não foi possível eliminar.',
      kpiArticlesPub: 'Artigos publicados',
      kpiFlashPub: 'Fio publicado',
      kpiTotal: 'total',
      kpiWireShown: 'na amostra (máx. 24)',
      kpiHeroes: 'Linhas hero',
      kpiTags: 'Etiquetas',
      kpiAuthors: 'Autores',
      analyticsTitle: 'Tráfego ao vivo',
      analyticsLead:
        'Visualizações recentes neste processo Nexus. O IP fica só no servidor; o SSE ao vivo não o envia.',
      colTime: 'Hora',
      colPath: 'Caminho',
      colHost: 'Host',
      colRef: 'Referrer',
      colUa: 'User agent',
      colIp: 'IP',
      liveBadge: 'Ao vivo',
      emptyVisits: 'Ainda sem visitas — abra o site público noutro separador.',
      articleListTitle: 'Artigos',
      articleBackList: '← Artigos',
      articleNew: 'Novo artigo',
      articleEdit: 'Editar artigo',
      articleColTitle: 'Título',
      articleColSlug: 'Slug',
      articleColStatus: 'Estado',
      articleColUpdated: 'Atualizado',
      articleStatusPub: 'Publicado',
      articleStatusDraft: 'Rascunho',
      articleEmpty: 'Ainda não há artigos. Crie um para começar.',
      articleFormTitleLabel: 'Título',
      articleFormSlugLabel: 'Slug URL',
      articleFormExcerptLabel: 'Resumo',
      articleFormContentLabel: 'Corpo (HTML ou texto)',
      articleFormCoverLabel: 'URL da imagem de capa',
      articleFormCoverAltLabel: 'Texto alternativo',
      articleFormReadTimeLabel: 'Tempo de leitura (min)',
      articleFormAuthorLabel: 'Autor',
      articleFormAuthorNone: '— Nenhum —',
      articleFormTagsLabel: 'Etiquetas',
      articleFormPublishedLabel: 'Publicado',
      articleFormSave: 'Guardar',
      articleFormDelete: 'Eliminar artigo',
      articleFormDeleteConfirm: 'Eliminar este artigo permanentemente?',
      articleErrSave: 'Não foi possível guardar. Verifique os campos e a ligação ao CMS.',
      adminMediaUploadLabel: 'Ficheiro de imagem (Cloudinary)',
      adminMediaUploadHint:
        'O envio vai para o API e preenche o URL da capa. Também pode colar um URL manualmente.',
      adminMediaUploadErr: 'Falha ao enviar a imagem. Verifique a sessão de admin e o API (CORS).',
      flashListTitle: 'Fio / flashes',
      flashBackList: '← Fio',
      flashNew: 'Novo flash',
      flashEdit: 'Editar flash',
      flashColTitle: 'Título',
      flashColSlug: 'Slug',
      flashColStatus: 'Estado',
      flashColUpdated: 'Atualizado',
      flashEmpty: 'Ainda não há itens de fio.',
      flashStatusPub: 'Publicado',
      flashStatusDraft: 'Rascunho',
      flashFormTitleLabel: 'Título',
      flashFormSlugLabel: 'Slug (opcional; gerado a partir do título se vazio)',
      flashFormSummaryLabel: 'Resumo',
      flashFormSourceLabel: 'Etiqueta da fonte',
      flashFormSourceUrlLabel: 'URL da fonte',
      flashFormHackLabel: 'Nota',
      flashFormPublishedLabel: 'Publicado',
      flashFormSave: 'Guardar',
      flashFormDelete: 'Eliminar',
      flashFormDeleteConfirm: 'Eliminar este flash permanentemente?',
      flashErrSave: 'Não foi possível guardar. Verifique os campos e a ligação ao CMS.',
      heroListTitle: 'Banners hero',
      heroBackList: '← Hero',
      heroNew: 'Novo bloco hero',
      heroEdit: 'Editar hero',
      heroColSlug: 'Slug',
      heroColHeadline: 'Manchete',
      heroColStatus: 'Estado',
      heroColUpdated: 'Atualizado',
      heroEmpty: 'Ainda não há blocos hero.',
      heroStatusPub: 'Publicado',
      heroStatusDraft: 'Rascunho',
      heroFormSlugLabel: 'Slug',
      heroFormSlugHint: 'Chave estável (ex.: home). Não pode ser alterado após guardar.',
      heroFormKickerLabel: 'Linha fina',
      heroFormHeadlineLabel: 'Manchete',
      heroFormSubheadlineLabel: 'Subtítulo',
      heroFormBodyLabel: 'Corpo',
      heroFormBodySecondaryLabel: 'Corpo secundário',
      heroFormImageUrlLabel: 'URL da imagem',
      heroFormFooterCtaLabel: 'CTA rodapé (texto)',
      heroFormFooterCtaHrefLabel: 'CTA rodapé (URL)',
      heroFormPublishedLabel: 'Publicado',
      heroFormSave: 'Guardar',
      heroFormDelete: 'Eliminar hero',
      heroFormDeleteConfirm: 'Eliminar este bloco hero permanentemente?',
      heroErrSave: 'Não foi possível guardar. Verifique os campos e a ligação ao CMS.',
    },
  };
  const key: Locale =
    locale === 'en' || locale === 'es' || locale === 'pt' ? locale : DEFAULT_LOCALE;
  return t[key] ?? t.en;
}
