/**
 * Nexus Type Generator
 *
 * Auto-generates `nexus-types.d.ts` — the invisible glue between server and client.
 *
 * What it generates:
 *   - Route params types: `type RouteParams['/blog/[slug]'] = { slug: string }`
 *   - Server Action types: `type Actions = { updateProfile: (f: FormData) => Promise<{success:boolean}> }`
 *   - API route return types: inferred from the route's render function
 *   - `$sync` type bindings for the reactive sync rune
 *
 * Usage: runs automatically on `nexus dev` and `nexus build`.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { parse } from '@nexus/compiler';
import { buildRouteManifest } from '@nexus/router';
import type { RouteManifest } from '@nexus/router';
import type { ServerAction } from '@nexus/compiler';

export interface GenerateTypesOptions {
  root: string;
  outFile?: string;
}

/**
 * Main entry: scans the project and writes `nexus-types.d.ts`.
 */
export async function generateTypes(opts: GenerateTypesOptions): Promise<void> {
  const routesDir = join(opts.root, 'src', 'routes');
  const outFile = opts.outFile ?? join(opts.root, '.nexus', 'nexus-types.d.ts');

  await mkdir(join(opts.root, '.nexus'), { recursive: true });

  const manifest = await buildRouteManifest(routesDir);
  const output = await buildTypeOutput(manifest, routesDir);

  await writeFile(outFile, output, 'utf-8');
  console.log(`  [Nexus Types] Generated ${relative(opts.root, outFile)}`);
}

async function buildTypeOutput(
  manifest: RouteManifest,
  routesDir: string,
): Promise<string> {
  const lines: string[] = [];

  lines.push(`// nexus-types.d.ts — AUTO-GENERATED by @nexus/types`);
  lines.push(`// DO NOT EDIT — re-generated on every build`);
  lines.push(`// Add this file to your tsconfig "include" array.`);
  lines.push('');
  lines.push(`import type { NexusContext } from '@nexus/server';`);
  lines.push('');

  // ── Route Params ──────────────────────────────────────────────────────────
  lines.push('// ── Route Params ────────────────────────────────────────────────────────────');
  lines.push('export type RouteParams = {');
  for (const route of manifest.routes) {
    if (route.isLayout) continue;
    const paramsType =
      route.params.length > 0
        ? `{ ${route.params.map((p) => `${p}: string`).join('; ')} }`
        : 'Record<never, never>';
    lines.push(`  '${route.pattern}': ${paramsType};`);
  }
  lines.push('};');
  lines.push('');

  // ── Server Actions per route ───────────────────────────────────────────────
  lines.push('// ── Server Actions ──────────────────────────────────────────────────────────');
  const allActions: ActionTypeEntry[] = [];

  for (const route of manifest.routes) {
    try {
      const src = await readFile(route.filepath, 'utf-8');
      const parsed = parse(src, route.filepath);

      if (parsed.serverActions.length === 0) continue;

      for (const action of parsed.serverActions) {
        allActions.push({
          name: action.name,
          route: route.pattern,
          params: action.params,
          returnType: inferReturnType(action),
        });
      }
    } catch {
      // File might not be readable — skip
    }
  }

  if (allActions.length > 0) {
    lines.push('export type NexusActions = {');
    for (const a of allActions) {
      const paramStr = a.params.length > 0 ? a.params.join(', ') : '';
      lines.push(`  /** @route ${a.route} */`);
      lines.push(`  '${a.name}': (${paramStr}) => ${a.returnType};`);
    }
    lines.push('};');
  } else {
    lines.push('export type NexusActions = Record<never, never>;');
  }

  lines.push('');

  // ── Typed useAction hook ───────────────────────────────────────────────────
  lines.push('// ── useAction — typed client stub ───────────────────────────────────────────');
  lines.push(`declare module '@nexus/runtime' {`);
  lines.push(`  export function useAction<K extends keyof NexusActions>(`);
  lines.push(`    name: K`);
  lines.push(`  ): {`);
  lines.push(`    execute: NexusActions[K];`);
  lines.push(`    pending: boolean;`);
  lines.push(`    error: string | null;`);
  lines.push(`  };`);
  lines.push(`}`);
  lines.push('');

  // ── Typed Router ──────────────────────────────────────────────────────────
  lines.push('// ── Typed Router ─────────────────────────────────────────────────────────────');
  lines.push(`declare module '@nexus/runtime/router' {`);
  lines.push(`  export function navigate<R extends keyof RouteParams>(`);
  lines.push(`    route: R,`);
  lines.push(`    params: RouteParams[R]`);
  lines.push(`  ): void;`);
  lines.push(`}`);
  lines.push('');

  // ── Form Action types ─────────────────────────────────────────────────────
  lines.push('// ── Typed form action={fn} ───────────────────────────────────────────────────');
  lines.push(`type ActionHandler<TInput = FormData, TResult = void> = (`);
  lines.push(`  input: TInput,`);
  lines.push(`  ctx: NexusContext`);
  lines.push(`) => Promise<TResult>;`);
  lines.push('');
  lines.push('export type { ActionHandler };');
  lines.push('');

  // ── $sync type bindings ───────────────────────────────────────────────────
  lines.push('// ── $sync rune bindings ─────────────────────────────────────────────────────');
  lines.push(`declare global {`);
  lines.push(`  function $sync<T>(`);
  lines.push(`    key: string,`);
  lines.push(`    opts?: {`);
  lines.push(`      default?: T;`);
  lines.push(`      persist?: 'cookie' | 'session' | 'db';`);
  lines.push(`      optimistic?: boolean;`);
  lines.push(`    }`);
  lines.push(`  ): { value: T; pending: boolean; error: string | null };`);
  lines.push('');
  lines.push(`  function $optimistic<T>(`);
  lines.push(`    signal: { value: T },`);
  lines.push(`    action: () => Promise<T | void>,`);
  lines.push(`    rollback?: T`);
  lines.push(`  ): void;`);
  lines.push(`}`);

  return lines.join('\n') + '\n';
}

interface ActionTypeEntry {
  name: string;
  route: string;
  params: string[];
  returnType: string;
}

/**
 * Infers the return type of a server action from its body.
 * For now: detects `return { ... }` patterns and maps to object literals.
 * Future: use TS compiler API for perfect inference.
 */
function inferReturnType(action: ServerAction): string {
  const body = action.body;

  // Detect explicit return type from JSDoc-style comment
  const docMatch = /\/\*\*\s*@returns\s+\{([^}]+)\}\s*\*\//.exec(body);
  if (docMatch?.[1]) return `Promise<${docMatch[1].trim()}>`;

  // Detect `return { success: true/false }` pattern
  if (/return\s*\{\s*success/.test(body)) return 'Promise<{ success: boolean }>';

  // Detect `return { data:` pattern
  if (/return\s*\{\s*data:/.test(body)) return 'Promise<{ data: unknown }>';

  // Detect `return Response.json(` pattern
  if (/return\s+Response\.json\(/.test(body)) return 'Promise<Response>';

  // Detect `return null` or `return undefined`
  if (/return\s+(null|undefined)/.test(body)) return 'Promise<null>';

  // Default: unknown — developer should annotate
  return 'Promise<unknown>';
}
