/**
 * Nexus Marketplace — `nexus add <block>`
 *
 * Installs pre-built "Nexus Blocks": components, auth systems, DB schemas,
 * and more — directly scaffolded into your project.
 *
 * Registry format (fetched from GitHub or local for offline):
 *   blocks.json → { id, name, description, files: [{ path, content }] }
 *
 * Usage:
 *   nexus add auth         → Full auth system (middleware + routes + actions)
 *   nexus add pokecard     → Pre-styled island with Runes configured
 *   nexus add analytics    → Privacy-first page-view tracker
 *   nexus add rate-limit   → Edge rate limiter middleware
 *   nexus add              → Interactive picker (lists available blocks)
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { createInterface } from 'node:readline';

const c = {
  reset: '\x1b[0m', bold: '\x1b[1m', dim: '\x1b[2m',
  red: '\x1b[31m', green: '\x1b[32m', yellow: '\x1b[33m',
  mag: '\x1b[35m', cyan: '\x1b[36m', gray: '\x1b[90m',
};

// ── Block registry (bundled + optionally fetched from remote) ─────────────────

export interface NexusBlock {
  id:          string;
  name:        string;
  category:    'auth' | 'ui' | 'data' | 'middleware' | 'analytics';
  description: string;
  tags:        string[];
  files:       BlockFile[];
  postInstall?: string;
}

interface BlockFile {
  path:    string;  // relative to project root (e.g. src/routes/login/+page.nx)
  content: string;
}

// ── Built-in blocks ───────────────────────────────────────────────────────────

const BLOCKS: NexusBlock[] = [
  {
    id:          'auth',
    name:        'Nexus Auth',
    category:    'auth',
    description: 'Full auth system: login/register routes + session middleware + Server Actions',
    tags:        ['authentication', 'sessions', 'middleware'],
    postInstall: 'Set AUTH_SECRET in your .env file and run nexus build.',
    files: [
      {
        path: 'src/lib/auth.ts',
        content: `/**
 * Nexus Auth — Server-side session helpers.
 * Generated by: nexus add auth
 */
import type { NexusContext } from '@nexus/server';

export interface Session {
  userId:   string;
  email:    string;
  role:     'user' | 'admin';
  expiresAt: number;
}

export function getSession(ctx: NexusContext): Session | null {
  const cookie = ctx.request.headers.get('cookie');
  if (!cookie) return null;
  const match = /nx-session=([^;]+)/.exec(cookie);
  if (!match) return null;
  try {
    return JSON.parse(atob(match[1])) as Session;
  } catch { return null; }
}

export function requireSession(ctx: NexusContext): Session {
  const session = getSession(ctx);
  if (!session || session.expiresAt < Date.now()) {
    ctx.redirect('/login');
    throw new Error('Unreachable'); // redirect throws
  }
  return session;
}
`,
      },
      {
        path: 'src/routes/login/+page.nx',
        content: `---
import { createAction } from '@nexus/server';
import { defineHead } from '@nexus/head';

defineHead({ title: 'Login — Nexus Auth' });

const loginAction = createAction(async (formData: FormData, ctx) => {
  const email    = formData.get('email')?.toString() ?? '';
  const password = formData.get('password')?.toString() ?? '';

  // TODO: validate against your DB
  if (email && password) {
    ctx.setCookie('nx-session', btoa(JSON.stringify({
      userId: '1', email, role: 'user', expiresAt: Date.now() + 86400_000
    })), { httpOnly: true, sameSite: 'lax' });
    ctx.redirect('/');
  }
}, { idempotent: false, race: 'reject' });
---

<main class="auth-page">
  <form method="POST" class="auth-form">
    <h1>Sign in</h1>
    <input type="email" name="email" placeholder="Email" required />
    <input type="password" name="password" placeholder="Password" required />
    <button type="submit">Sign in</button>
  </form>
</main>

<style>
  .auth-page  { display:flex; align-items:center; justify-content:center; min-height:80vh }
  .auth-form  { display:flex; flex-direction:column; gap:12px; width:320px }
  .auth-form h1 { font-size:24px; font-weight:700; margin-bottom:8px }
  .auth-form input { padding:10px 14px; border:1px solid var(--border,#e5e7eb); border-radius:8px }
  .auth-form button { padding:10px; background:#7c3aed; color:#fff; border:none; border-radius:8px; font-weight:600; cursor:pointer }
</style>
`,
      },
      {
        path: 'src/middleware/auth.ts',
        content: `/**
 * Nexus Auth Middleware — protects routes requiring a session.
 * Generated by: nexus add auth
 */
import { defineMiddleware } from '@nexus/middleware';
import { getSession } from '../lib/auth.js';

export const authMiddleware = defineMiddleware(async (ctx, next) => {
  const session = getSession(ctx);
  const isProtected = ctx.request.url.includes('/dashboard') ||
                      ctx.request.url.includes('/profile');

  if (isProtected && !session) {
    return ctx.redirect('/login');
  }
  return next();
});
`,
      },
    ],
  },

  {
    id:          'analytics',
    name:        'Nexus Analytics',
    category:    'analytics',
    description: 'Privacy-first page-view counter using Server Actions + Shield Cache.',
    tags:        ['analytics', 'privacy', 'pageviews'],
    postInstall: 'Add <Analytics /> to your root layout.',
    files: [
      {
        path: 'src/components/Analytics.nx',
        content: `---
// Privacy-first analytics — no cookies, no fingerprinting.
// Generated by: nexus add analytics
import { cache } from '@nexus/runtime';
const key = 'nx-' + crypto.randomUUID().slice(0, 8); // ephemeral session id
---

<script client:idle>
// Fires a page-view beacon on mount (client:idle = after page paint)
const path = window.location.pathname;
navigator.sendBeacon?.('/_nexus/action/track-view', JSON.stringify({ path }));
</script>
`,
      },
      {
        path: 'src/routes/api/analytics/+page.nx',
        content: `---
import { createAction, registerAction } from '@nexus/server';

// In-memory counter (replace with DB in production)
const views = new Map<string, number>();

registerAction('track-view', async (input: { path: string }) => {
  views.set(input.path, (views.get(input.path) ?? 0) + 1);
}, { idempotent: false });

const data = Object.fromEntries(views);
---
<pre>{JSON.stringify(data, null, 2)}</pre>
`,
      },
    ],
  },

  {
    id:          'pokecard',
    name:        'PokéCard Island',
    category:    'ui',
    description: 'Pre-styled Pokémon card island with shiny toggle Rune. Demo component.',
    tags:        ['ui', 'island', 'demo', 'runes'],
    files: [
      {
        path: 'src/components/PokéCard.nx',
        content: `---
export interface Props {
  id:     number;
  name:   string;
  sprite: string;
  types:  string[];
  color:  string;
}
const { id, name, sprite, types, color } = $props<Props>();
---

<script>
let shiny = $state(false);
</script>

<a href="/pokemon/{id}" class="pokecard" style="--color: {color}">
  <div class="card-bg">
    <img src="{sprite}" alt="{name}" width="120" height="120" />
    <button onclick="{() => shiny = !shiny}" class="shiny-btn">
      {shiny ? '✨ Shiny' : '✨ Normal'}
    </button>
  </div>
  <div class="card-body">
    <span class="dex-num">#{String(id).padStart(3, '0')}</span>
    <h3>{name}</h3>
    <div class="types">
      {#each types as type}
        <span class="type-badge type-{type}">{type}</span>
      {/each}
    </div>
  </div>
</a>

<style>
  .pokecard { display:block; border-radius:16px; overflow:hidden; text-decoration:none; color:inherit; background:var(--surface, #13131f); border:1px solid var(--border, #1e1e30); transition:transform .2s }
  .pokecard:hover { transform:translateY(-4px) }
  .card-bg { background:linear-gradient(135deg, color-mix(in srgb, var(--color) 20%, transparent), transparent); padding:20px; display:flex; flex-direction:column; align-items:center; gap:8px }
  .card-body { padding:12px 16px 16px }
  .dex-num { font-size:11px; color:#64748b; font-family:monospace }
  h3 { font-size:16px; font-weight:700; text-transform:capitalize; margin:4px 0 8px }
  .types { display:flex; gap:4px; flex-wrap:wrap }
  .type-badge { padding:2px 10px; border-radius:999px; font-size:11px; font-weight:700; background:#374151; color:#fff }
  .shiny-btn { padding:4px 12px; border-radius:999px; border:1px solid #374151; background:transparent; color:#94a3b8; font-size:11px; cursor:pointer }
</style>
`,
      },
    ],
  },

  {
    id:          'rate-limit',
    name:        'Edge Rate Limiter',
    category:    'middleware',
    description: 'IP-based rate limiting middleware for API routes and Server Actions.',
    tags:        ['security', 'middleware', 'edge'],
    files: [
      {
        path: 'src/middleware/rate-limit.ts',
        content: `/**
 * Nexus Edge Rate Limiter — in-memory sliding window.
 * Generated by: nexus add rate-limit
 *
 * For production, replace the Map with an Upstash/Redis adapter.
 */
import { defineMiddleware } from '@nexus/middleware';

const windows = new Map<string, { count: number; reset: number }>();

export function createRateLimit(opts: {
  requests: number;
  windowMs:  number;
  message?:  string;
}) {
  return defineMiddleware(async (ctx, next) => {
    const ip  = ctx.request.headers.get('x-forwarded-for')?.split(',')[0].trim() ?? 'unknown';
    const now = Date.now();
    const win = windows.get(ip);

    if (!win || now > win.reset) {
      windows.set(ip, { count: 1, reset: now + opts.windowMs });
      return next();
    }

    if (win.count >= opts.requests) {
      return new Response(
        JSON.stringify({ error: opts.message ?? 'Too Many Requests' }),
        { status: 429, headers: { 'content-type': 'application/json', 'retry-after': String(Math.ceil((win.reset - now) / 1000)) } }
      );
    }

    win.count++;
    return next();
  });
}

// Default: 100 req / 60s per IP
export const rateLimitMiddleware = createRateLimit({ requests: 100, windowMs: 60_000 });
`,
      },
    ],
  },
];

// ── CLI logic ─────────────────────────────────────────────────────────────────

function listBlocks(): void {
  console.log(`\n  ${c.mag}${c.bold}◆ Nexus Marketplace${c.reset}\n`);
  const byCategory = new Map<string, NexusBlock[]>();
  for (const block of BLOCKS) {
    if (!byCategory.has(block.category)) byCategory.set(block.category, []);
    byCategory.get(block.category)!.push(block);
  }
  for (const [cat, blocks] of byCategory) {
    console.log(`  ${c.cyan}${cat}${c.reset}`);
    for (const b of blocks) {
      console.log(`    ${c.bold}nexus add ${b.id}${c.reset}  ${c.dim}${b.description}${c.reset}`);
    }
    console.log('');
  }
  console.log(`  ${c.dim}Run ${c.reset}${c.bold}nexus add <id>${c.reset}${c.dim} to install a block.${c.reset}\n`);
}

async function installBlock(blockId: string, root: string): Promise<void> {
  const block = BLOCKS.find((b) => b.id === blockId);
  if (!block) {
    console.error(`\n  ${c.red}✖${c.reset}  Block "${blockId}" not found.\n`);
    listBlocks();
    process.exit(1);
  }

  console.log(`\n  ${c.mag}${c.bold}◆ Nexus Marketplace${c.reset}  Installing ${c.bold}${block.name}${c.reset}...\n`);

  for (const file of block.files) {
    const fullPath = join(root, file.path);
    await mkdir(dirname(fullPath), { recursive: true });
    await writeFile(fullPath, file.content, 'utf-8');
    console.log(`  ${c.green}✔${c.reset}  Created ${c.cyan}${file.path}${c.reset}`);
  }

  if (block.postInstall) {
    console.log(`\n  ${c.yellow}→${c.reset}  ${block.postInstall}`);
  }

  console.log(`\n  ${c.green}◆${c.reset}  ${block.name} installed successfully.\n`);
}

/** Interactive block picker when no ID is given */
async function pickBlock(root: string): Promise<void> {
  listBlocks();
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const answer = await new Promise<string>((resolve) => {
    rl.question(`  Which block? ${c.dim}(id)${c.reset} `, resolve);
  });
  rl.close();
  await installBlock(answer.trim(), root);
}

/** Entry point called by packages/cli/src/bin.ts */
export async function runAdd(opts: { blockId?: string; root: string }): Promise<void> {
  if (!opts.blockId) {
    await pickBlock(opts.root);
  } else {
    await installBlock(opts.blockId, opts.root);
  }
}
